import { UserProfile, FunnelAutomationRule, FinanceMetrics, ModerationReport, ConciergeCase, AuditLogItem } from '../types';

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'p-maria',
    name: 'Maria Helena',
    age: 64,
    gender: 'mulher',
    city: 'Rio de Janeiro',
    state: 'RJ',
    profession: 'Professora aposentada',
    statusText: 'Viúva',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Gosto de cinema, viagens culturais, boa gastronomia e conversas profundas. Procuro companheirismo com leveza para viver esta nova fase da vida com plenitude.',
    interests: ['Cinema', 'Viagens', 'Teatro', 'Gastronomia', 'Literatura'],
    values: ['Família', 'Respeito', 'Lealdade', 'Diálogo'],
    lifestyle: ['Programas tranquilos', 'Viagens planejadas', 'Passeios culturais'],
    children: '3 filhos adultos',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: true,
    ageAssured: true,
    minAge: 58,
    maxAge: 70,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'PLUS',
    lastActiveDays: 0,
    funnelStage: 'active_paid',
    phone: '(21) 99842-1209',
    email: 'maria.helena@email.com',
    createdAt: '2026-08-10T14:20:00Z',
    ownerNotes: ['Cliente engajada no plano Plus. Prioriza parceiros com formação cultural e hábitos tranquilos.'],
    crmTags: ['VIP', 'Perfil Verificado', 'Alta Resposta'],
    documentStatus: 'verified',
    documentType: 'CNH Digital',
    documentNumberMasked: '***.482.910-**',
    totalMatchesCount: 4,
    totalMessagesCount: 38,
    lifetimeValue: 237.00
  },
  {
    id: 'p-emanuel',
    name: 'Emanuel Rocha',
    age: 61,
    gender: 'homem',
    city: 'Rio de Janeiro',
    state: 'RJ',
    profession: 'Marceneiro e empresário',
    statusText: 'Divorciado',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Sou uma pessoa serena, aprecio arte sacra, música brasileira, gastronomia e fazer coisas à moda antiga. Valorizo presença física e sinceridade.',
    interests: ['Teatro', 'Viagens', 'Gastronomia', 'Música', 'Café'],
    values: ['Família', 'Respeito', 'Companheirismo'],
    lifestyle: ['Programas tranquilos', 'Passeios culturais'],
    children: '2 filhos adultos',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: true,
    ageAssured: true,
    minAge: 55,
    maxAge: 68,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'CONCIERGE',
    lastActiveDays: 0,
    funnelStage: 'active_paid',
    phone: '(21) 98711-3450',
    email: 'emanuel.rocha@marcenaria.com',
    createdAt: '2026-08-15T09:30:00Z',
    ownerNotes: ['Assinou plano Concierge VIP. Solicitou curadoria humana para encontros no Leblon/Ipanema.'],
    crmTags: ['Concierge VIP', 'Alta Afinidade', 'Doc Aprovado'],
    documentStatus: 'verified',
    documentType: 'RG',
    documentNumberMasked: '***.723.190-**',
    totalMatchesCount: 6,
    totalMessagesCount: 52,
    lifetimeValue: 1047.00
  },
  {
    id: 'p-teresa',
    name: 'Teresa Martins',
    age: 57,
    gender: 'mulher',
    city: 'Brasília',
    state: 'DF',
    profession: 'Arquiteta e Urbanista',
    statusText: 'Divorciada',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Aprecio arquitetura modernista, exposições de arte contemporânea, trilhas e cozinhar para bons amigos. Busco alguém gentil, curioso e independente.',
    interests: ['Arte', 'Viagens', 'Gastronomia', 'Cinema', 'Natureza'],
    values: ['Respeito', 'Curiosidade', 'Família', 'Autonomia'],
    lifestyle: ['Programas culturais', 'Vida social moderada'],
    children: '1 filha adulta',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: true,
    ageAssured: true,
    minAge: 53,
    maxAge: 65,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'FREE',
    lastActiveDays: 1,
    funnelStage: 'in_conversation',
    phone: '(61) 99124-8833',
    email: 'teresa.martins@arq.com',
    createdAt: '2026-08-20T11:00:00Z',
    ownerNotes: ['Candidata forte para upgrade de plano. Conversando com Paulo Sérgio.'],
    crmTags: ['Potencial Plus', 'Verificada'],
    documentStatus: 'verified',
    documentType: 'CNH Digital',
    documentNumberMasked: '***.551.401-**',
    totalMatchesCount: 2,
    totalMessagesCount: 24,
    lifetimeValue: 0
  },
  {
    id: 'p-paulo',
    name: 'Paulo Sérgio',
    age: 59,
    gender: 'homem',
    city: 'Brasília',
    state: 'DF',
    profession: 'Auditor Fiscal',
    statusText: 'Divorciado',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Caminhadas matinais no Parque da Cidade, bom café e leituras históricas. Busco construir cumplicidade e momentos de paz.',
    interests: ['Viagens', 'Café', 'Natureza', 'Música instrumental', 'Livros'],
    values: ['Respeito', 'Autonomia', 'Lealdade', 'Diálogo'],
    lifestyle: ['Vida social moderada', 'Natureza', 'Rotina saudável'],
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: true,
    ageAssured: true,
    minAge: 52,
    maxAge: 66,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'PLUS',
    lastActiveDays: 0,
    funnelStage: 'in_conversation',
    phone: '(61) 98112-9090',
    email: 'paulo.sergio@gov.br',
    createdAt: '2026-08-18T16:15:00Z',
    ownerNotes: ['Perfil ativo diariamente. Muito respeitoso nos contatos.'],
    crmTags: ['Assinante Plus', 'Doc Aprovado'],
    documentStatus: 'verified',
    documentType: 'RG',
    documentNumberMasked: '***.819.331-**',
    totalMatchesCount: 3,
    totalMessagesCount: 41,
    lifetimeValue: 158.00
  },
  {
    id: 'p-carlos',
    name: 'Carlos Henrique',
    age: 58,
    gender: 'homem',
    city: 'Niterói',
    state: 'RJ',
    profession: 'Comerciante náutico',
    statusText: 'Separado',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Adoro mar, praia de manhã cedo e restaurantes com comida brasileira. Procuro alguém autêntica para compartilhar bons passeios e projetos de vida.',
    interests: ['Música', 'Gastronomia', 'Viagens', 'Natureza', 'Velejo'],
    values: ['Família', 'Trabalho', 'Respeito'],
    lifestyle: ['Vida social moderada', 'Passeios ao ar livre'],
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: false,
    ageAssured: true,
    minAge: 50,
    maxAge: 64,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'FREE',
    lastActiveDays: 1,
    funnelStage: 'pending_verification',
    phone: '(21) 97134-5511',
    email: 'carlos.henrique@nautica.com',
    createdAt: '2026-09-02T10:00:00Z',
    ownerNotes: ['Enviou CNH para aprovação. Aguardando verificação da nitidez do documento.'],
    crmTags: ['Doc Pendente', 'Lead Quente'],
    documentStatus: 'pending',
    documentType: 'CNH Física',
    documentNumberMasked: '***.932.117-**',
    totalMatchesCount: 1,
    totalMessagesCount: 4,
    lifetimeValue: 0
  },
  {
    id: 'p-beatriz',
    name: 'Beatriz Campos',
    age: 44,
    gender: 'mulher',
    city: 'São Paulo',
    state: 'SP',
    profession: 'Advogada Tributária',
    statusText: 'Solteira',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Cinema aos finais de semana, corrida matinal no Ibirapuera e viagens gastronômicas. Busco alguém decidido, leal e com bom humor.',
    interests: ['Cinema', 'Viagens', 'Natureza', 'Livros', 'Vinho'],
    values: ['Respeito', 'Diálogo', 'Autonomia', 'Lealdade'],
    lifestyle: ['Vida social moderada', 'Passeios ao ar livre'],
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: true,
    ageAssured: true,
    minAge: 40,
    maxAge: 53,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'PLUS',
    lastActiveDays: 0,
    funnelStage: 'active_paid',
    phone: '(11) 98844-0199',
    email: 'beatriz.campos@adv.sp.com',
    createdAt: '2026-08-25T14:40:00Z',
    ownerNotes: ['Excelente perfil, alto índice de aceitação. Assinante Plus ativa.'],
    crmTags: ['Perfil Estrela', 'Assinante Plus'],
    documentStatus: 'verified',
    documentType: 'OAB / Identidade',
    documentNumberMasked: '***.402.778-**',
    totalMatchesCount: 5,
    totalMessagesCount: 30,
    lifetimeValue: 158.00
  },
  {
    id: 'p-julio',
    name: 'Júlio César',
    age: 63,
    gender: 'homem',
    city: 'São Paulo',
    state: 'SP',
    profession: 'Diretor Administrativo',
    statusText: 'Viúvo',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Museus, feiras de antiguidades e uma mesa farta com boa conversa. Quero conhecer alguém que valorize a cumplicidade sincera.',
    interests: ['Museus', 'Viagens', 'Gastronomia', 'Cinema', 'História'],
    values: ['Respeito', 'Família', 'Diálogo', 'Fidelidade'],
    lifestyle: ['Programas culturais', 'Viagens planejadas'],
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: true,
    ageAssured: true,
    minAge: 56,
    maxAge: 68,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'CONCIERGE',
    lastActiveDays: 2,
    funnelStage: 'active_paid',
    phone: '(11) 97200-1122',
    email: 'julio.cesar@gestao.com',
    createdAt: '2026-08-01T08:00:00Z',
    ownerNotes: ['Cliente Concierge VIP. Matchmaker selecionando candidatas na Grande SP.'],
    crmTags: ['VIP', 'Concierge', 'Alta Renda'],
    documentStatus: 'verified',
    documentType: 'Passaporte',
    documentNumberMasked: '***.339.818-**',
    totalMatchesCount: 7,
    totalMessagesCount: 65,
    lifetimeValue: 1047.00
  },
  {
    id: 'p-lucia',
    name: 'Lúcia Andrade',
    age: 60,
    gender: 'mulher',
    city: 'São Paulo',
    state: 'SP',
    profession: 'Médica Cardiologista',
    statusText: 'Divorciada',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Aprecio música clássica, concertos, literatura contemporânea e viagens em cidades históricas. Valorizo inteligência e carinho.',
    interests: ['Livros', 'Música', 'Viagens', 'Teatro', 'Arte'],
    values: ['Diálogo', 'Respeito', 'Autonomia', 'Afeto'],
    lifestyle: ['Programas culturais', 'Viagens planejadas'],
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: true,
    ageAssured: true,
    minAge: 56,
    maxAge: 69,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'FREE',
    lastActiveDays: 1,
    funnelStage: 'matched_inactive',
    phone: '(11) 99311-4477',
    email: 'lucia.andrade@med.usp.br',
    createdAt: '2026-09-05T13:20:00Z',
    ownerNotes: ['Teve match com Júlio César há 3 dias mas nenhum dos dois mandou mensagem ainda. Disparar quebra-gelo.'],
    crmTags: ['Match Parado', 'Lead Quente'],
    documentStatus: 'verified',
    documentType: 'CRM Médico',
    documentNumberMasked: '***.129.408-**',
    totalMatchesCount: 3,
    totalMessagesCount: 8,
    lifetimeValue: 0
  },
  {
    id: 'p-claudio',
    name: 'Cláudio Mendes',
    age: 62,
    gender: 'homem',
    city: 'Belo Horizonte',
    state: 'MG',
    profession: 'Perito Contábil',
    statusText: 'Divorciado',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Adoro a gastronomia mineira, fins de semana em Ouro Preto e Tiradentes, e ouvir boas histórias. Procuro parceria madura e alegre.',
    interests: ['Cinema', 'Gastronomia', 'Viagens', 'História', 'Música mineira'],
    values: ['Respeito', 'Diálogo', 'Companheirismo'],
    lifestyle: ['Programas culturais', 'Viagens planejadas'],
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: true,
    ageAssured: true,
    minAge: 55,
    maxAge: 68,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'PLUS',
    lastActiveDays: 0,
    funnelStage: 'active_paid',
    phone: '(31) 99881-2290',
    email: 'claudio.mendes@contabil.mg.com',
    createdAt: '2026-08-12T17:00:00Z',
    ownerNotes: ['Assinante Plus recorrente. Muito bem avaliado nas conexões.'],
    crmTags: ['Plus', 'MG Líder'],
    documentStatus: 'verified',
    documentType: 'RG',
    documentNumberMasked: '***.662.906-**',
    totalMatchesCount: 4,
    totalMessagesCount: 29,
    lifetimeValue: 237.00
  },
  {
    id: 'p-helena-nova',
    name: 'Helena Demo',
    age: 54,
    gender: 'mulher',
    city: 'Brasília',
    state: 'DF',
    profession: 'Servidora Pública',
    statusText: 'Solteira',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Adoro cinema e passeios tranquilos.',
    interests: ['Cinema'],
    values: ['Respeito'],
    lifestyle: [],
    photoUrl: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=600&q=80',
    active: true,
    verified: false,
    ageAssured: true,
    minAge: 50,
    maxAge: 62,
    onboardingStep: 2,
    onboardingComplete: false,
    consentSensitive: false,
    tier: 'FREE',
    lastActiveDays: 2,
    funnelStage: 'lead_incomplete',
    phone: '(61) 99400-3311',
    email: 'helena.demo@servico.df.gov.br',
    createdAt: '2026-09-24T18:00:00Z',
    ownerNotes: ['Parou no passo 2 do cadastro. Faltam preencher interesses, valores e bio.'],
    crmTags: ['Onboarding Pendente', 'Funil Etapa 1'],
    documentStatus: 'not_sent',
    totalMatchesCount: 0,
    totalMessagesCount: 0,
    lifetimeValue: 0
  },
  {
    id: 'p-ricardo-churn',
    name: 'Ricardo Nunes',
    age: 49,
    gender: 'homem',
    city: 'Goiânia',
    state: 'GO',
    profession: 'Engenheiro Agrônomo',
    statusText: 'Divorciado',
    relationshipGoal: 'Relacionamento sério',
    bio: 'Viajo bastante a trabalho, aprecio o campo, boa culinária e conversas claras. Procuro alguém com propósitos definidos.',
    interests: ['Natureza', 'Gastronomia', 'Viagens', 'Música sertaneja de raiz'],
    values: ['Trabalho', 'Respeito', 'Família'],
    lifestyle: ['Natureza', 'Viagens frequentes'],
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=600&q=80',
    active: false,
    verified: true,
    ageAssured: true,
    minAge: 40,
    maxAge: 52,
    onboardingStep: 5,
    onboardingComplete: true,
    consentSensitive: false,
    tier: 'FREE',
    lastActiveDays: 7,
    funnelStage: 'at_risk_churn',
    phone: '(62) 98144-7722',
    email: 'ricardo.agro@go.com',
    createdAt: '2026-07-29T10:00:00Z',
    ownerNotes: ['Não abre o app há 7 dias. Está na régua de automação de reengajamento.'],
    crmTags: ['Risco Churn', 'Inativo > 5d'],
    documentStatus: 'verified',
    documentType: 'CNH',
    documentNumberMasked: '***.511.901-**',
    totalMatchesCount: 2,
    totalMessagesCount: 11,
    lifetimeValue: 79.00
  }
];

export const INITIAL_AUTOMATIONS: FunnelAutomationRule[] = [
  {
    id: 'auto-1',
    title: 'Recuperação de Onboarding Incompleto',
    description: 'Dispara lembrete amigável via WhatsApp/Push para quem parou no meio do cadastro há mais de 6 horas.',
    stageTrigger: 'lead_incomplete',
    actionType: 'whatsapp_message',
    messageTemplate: 'Olá {name}! Percebemos que faltam apenas 2 minutinhos para completar seu currículo afetivo no True Love. Pessoas compatíveis em {city} esperam para te conhecer!',
    delayHours: 6,
    isActive: true,
    executionCount: 142,
    conversionRate: 46.5,
    lastRun: '2026-09-29T19:30:00Z'
  },
  {
    id: 'auto-2',
    title: 'Alerta de Perfil com Afinidade Excepcional (>85%)',
    description: 'Avisa o usuário no app quando alguém na mesma cidade e faixa etária ideal tem mais de 85% de compatibilidade.',
    stageTrigger: 'active_unmatched',
    actionType: 'push_notification',
    messageTemplate: '✨ Uma pessoa muito especial com {affinity}% de afinidade foi apresentada para você em {city}. Venha ver o perfil!',
    delayHours: 1,
    isActive: true,
    executionCount: 388,
    conversionRate: 68.2,
    lastRun: '2026-09-29T21:00:00Z'
  },
  {
    id: 'auto-3',
    title: 'Quebra-Gelo para Match Parado (48h)',
    description: 'Quando duas pessoas dão match recíproco mas nenhuma inicia conversa em 48 horas, envia uma sugestão de assunto em comum.',
    stageTrigger: 'matched_inactive',
    actionType: 'push_notification',
    messageTemplate: 'Vocês têm {shared_interests} em comum! Que tal dar o primeiro oi com uma mensagem gentil?',
    delayHours: 48,
    isActive: true,
    executionCount: 95,
    conversionRate: 52.8,
    lastRun: '2026-09-29T18:15:00Z'
  },
  {
    id: 'auto-4',
    title: 'Aceleração de Upgrade para Plano Concierge VIP',
    description: 'Usuários com alta taxa de engajamento recebem convite com condição especial para curadoria humana.',
    stageTrigger: 'in_conversation',
    actionType: 'tier_discount',
    messageTemplate: 'Gostaria de ter um Matchmaker humano selecionando pretendentes perfeitos para sua rotina? Conheça o Concierge VIP True Love.',
    delayHours: 72,
    isActive: true,
    executionCount: 64,
    conversionRate: 23.4,
    lastRun: '2026-09-28T16:00:00Z'
  },
  {
    id: 'auto-5',
    title: 'Resgate de Usuário Inativo (Alerta de Churn)',
    description: 'Reativação carinhosa para usuários sem login há mais de 5 dias mostrando novos perfis que entraram na cidade.',
    stageTrigger: 'at_risk_churn',
    actionType: 'email_digest',
    messageTemplate: '{name}, novidades para você! 3 novas pessoas interessantes entraram no True Love em {city} esta semana. Sentimos sua falta!',
    delayHours: 120,
    isActive: true,
    executionCount: 77,
    conversionRate: 31.0,
    lastRun: '2026-09-29T10:00:00Z'
  }
];

export const INITIAL_FINANCE_METRICS: FinanceMetrics = {
  mrr: 28450.00,
  arr: 341400.00,
  totalPaidUsers: 245,
  totalFreeUsers: 830,
  plusUsersCount: 205,
  conciergeUsersCount: 40,
  churnRateMonthly: 3.2,
  averageLtv: 482.00,
  recentTransactions: [
    { id: 'tx-101', profileId: 'p-emanuel', profileName: 'Emanuel Rocha', amount: 349.00, tier: 'CONCIERGE', paymentMethod: 'credit_card', status: 'paid', date: '2026-09-29T15:20:00Z' },
    { id: 'tx-102', profileId: 'p-beatriz', profileName: 'Beatriz Campos', amount: 79.00, tier: 'PLUS', paymentMethod: 'apple_pay', status: 'paid', date: '2026-09-29T14:10:00Z' },
    { id: 'tx-103', profileId: 'p-julio', profileName: 'Júlio César', amount: 349.00, tier: 'CONCIERGE', paymentMethod: 'pix', status: 'paid', date: '2026-09-28T11:45:00Z' },
    { id: 'tx-104', profileId: 'p-claudio', profileName: 'Cláudio Mendes', amount: 79.00, tier: 'PLUS', paymentMethod: 'credit_card', status: 'paid', date: '2026-09-27T09:30:00Z' },
    { id: 'tx-105', profileId: 'p-maria', profileName: 'Maria Helena', amount: 79.00, tier: 'PLUS', paymentMethod: 'credit_card', status: 'paid', date: '2026-09-26T18:00:00Z' },
    { id: 'tx-106', profileId: 'p-paulo', profileName: 'Paulo Sérgio', amount: 79.00, tier: 'PLUS', paymentMethod: 'apple_pay', status: 'paid', date: '2026-09-25T13:20:00Z' }
  ]
};

export const INITIAL_REPORTS: ModerationReport[] = [
  {
    id: 'rep-01',
    reporterProfileId: 'p-maria',
    reportedProfileId: 'p-carlos',
    reason: 'Solicitação financeira precoce',
    details: 'Mencionou dificuldade financeira logo na terceira mensagem. Regra de segurança número 1 da plataforma.',
    status: 'open',
    createdAt: '2026-09-29T20:10:00Z'
  },
  {
    id: 'rep-02',
    reporterProfileId: 'p-teresa',
    reportedProfileId: 'p-ricardo-churn',
    reason: 'Linguagem incompatível com a política',
    details: 'Insistência inoportuna após recusa de encontro fora de local público.',
    status: 'reviewing',
    createdAt: '2026-09-28T14:00:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  { id: 'log-1', actor: 'Dono (Master)', role: 'super_admin', action: 'Aprovação de Documento', target: 'Maria Helena (p-maria)', timestamp: '2026-09-29 21:15', ipAddress: '189.40.12.9' },
  { id: 'log-2', actor: 'Dono (Master)', role: 'super_admin', action: 'Edição de Regra de Funil', target: 'Auto #2 (Alta Afinidade)', timestamp: '2026-09-29 20:45', ipAddress: '189.40.12.9' },
  { id: 'log-3', actor: 'Matchmaker Camila', role: 'matchmaker', action: 'Curadoria de Sugestões', target: 'Emanuel Rocha (p-emanuel)', timestamp: '2026-09-29 17:30', ipAddress: '201.86.104.3' },
  { id: 'log-4', actor: 'Suporte Rodrigo', role: 'support', action: 'Atendimento via Chat', target: 'Helena Demo (p-helena-nova)', timestamp: '2026-09-29 16:10', ipAddress: '177.18.23.41' }
];
